[program:moex]
# /root/moex-app can be a symlink to the actual project directory.
command=/root/moex-app/venv/bin/python3 /root/moex-app/main.py
directory=/root/moex-app
autostart=true
autorestart=true
startsecs=5
startretries=3
stderr_logfile=/root/moex-app/logs/moex.err.log
stdout_logfile=/root/moex-app/logs/moex.out.log
environment=PATH="/root/moex-app/venv/bin"
user=root
